# Site
name: 'NDJ en Español'
description: 'Información sobre la actualidad del mundo de los videojuegos y otros temas.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'noticiasdejuegosgh'
email: 'ndjespanol@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  
authors:
    sal:
      name:           NDJ en Español
      site:           https://noticiasdejuegos.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Cuenta oficial de NDJ en Español. Aquí realizamos todas nuestras publicaciones."
      email:          ndjespanol@gmail.com
      twitter:        https://twitter.com/NDJenEspanol

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]